### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by rurban** [PatrickCronin/Map-Functional#1]
I don't see a motivating testcase, and the description is bogus.

`perl -e'$_="x";%h=map{$_=>1}(0..3);print $_'` => x # global $_ is restored

`perl -e'sub x{$_="ouch"};$_="x";%h=map{$_=>x}(0..9);print $_'` => x # global $_ is restored

Do you just need a map with a lexical iteration variable other than `$_`?
`$_` is properly restored.

Something like `map sub($i){$i => 1} @array` for nested maps?

**Comment by PatrickCronin** [comment]
I love using `map` as the flexible and expressive idiom that it is, but lately I've grown wary of `map`s whose BLOCKs call subs/methods that are in different files, or that someone else may come along and change the implementation of later without consideration to it being called in a topic-vulnerable manner.

The goal is to provide an alternative to `map` with the same flexibility and expressiveness, but without concern of being affected by unintentional modifications of the global topic.

In this example, in which we clearly trample the topic for example purposes, an intermediate user may expect %calced to be something like `( 1 => XXX, 2 => XXX, 3 => XXX, 4 => XXX, 5 => XXX )`.
```
#!/usr/bin/env perl
use strict;
use warnings;
use DDP;

sub process_int {
    my $int = shift;
    $_ = 4;
    return $int * 2;
}

my %calced = map { $_ => process_int($_) } 1..5;

p %calced;
``` 
Imagine the surprise when %calced turns out to contain `(4 => 10)`.

Here's an example where trampling the global topic isn't so obvious. Again, an intermediate user might expect `%calced` to look something like `( 1 => XXX, 2 => XXX, 3 => XXX, 4 => XXX, 5 => XXX )`.
```
#!/usr/bin/env perl

use strict;
use warnings;
use DDP;

my $data_start = tell DATA;
my %calced = map { $_ => get_line_n($_) } 1..5;
p %calced;

sub get_line_n {
    my $int = shift;

    my $target_line;
    my $line_num = 0;
    while (<DATA>) {
        $line_num++;
        next if $line_num < $int;

        chomp;
        seek DATA, $data_start, 0;
        return $_;
    }
}

__DATA__
Line 1
Line 2
Line 3
Line 4
Line 5
Line 6
```

Actually, `%calced` contains
```
(
    'Line 1' => 'Line 1',
    'Line 2' => 'Line 2',
    'Line 3' => 'Line 3',
    'Line 4' => 'Line 4',
    'Line 5' => 'Line 5',
)
```

**Comment by rurban** [comment]
I see, the 2nd example is better.
Obviously in $_ => call, $_ should not be affected by the latter call. Left to right evaluation. 
I would call this a core bug. 
I think I'll fix that in cperl.

**Comment by PatrickCronin** [comment]
That is an interesting and unexpected consideration I hadn't thought of. The solution we're looking to provide with Map::Functional goes one step farther to provide `map`-like functionality with an iteration variable that is explicitly unavailable from subs/methods called within the BLOCK. So in something like `my %calced = fmap ($x) { $x => get_line_n($x) } 1..5;` I _wouldn't even have to think_ about what `get_line_n` does.

**Comment by PatrickCronin** [comment]
@rurban - Thanks very much for raising this issue; it's helped us to clarify the problem we're trying to solve, and it'll help us come up with test cases as well. Succinctly, we're looking to create a version of `map` that uses an explicitly-named lexical iteration variable.

Aside from the clarity resulting from being able to name the iteration variable, the benefits of the lexical nature of the iterator could be better illustrated by this example: `my %calced = fmap ($x) { calc_key($x) => get_line_n($x) } 1..5;` Regardless of whether `calc_key` or `get_line_n` modify the argument it receives, the value of `$x` should remain the same.

**Comment by rurban** [comment]
Yes, good call. In the meantime I'll try to fix that in cperl. So far I added a 'Odd number of map elements in hash assignment' warning. The order of evaluation to save $_ or the lexical itervar from being changed in subsequent mapblock entries is next. It will need adding mapwhile ops into mapblock lists statically. See https://github.com/perl11/cperl/issues/280 (tricky)

Having that on cpan is much better of course.
